# Generated by Django 2.2.1 on 2019-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='crew',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plane',
            name='name',
            field=models.CharField(default='Hack Plane', max_length=200),
        ),
    ]
